### ISSUE TITLE
Pipe output of Expand-Archive to null

### ISSUE THREAD

**Issue by mattkur** [jhowardmsft/docker-w2wCIScripts#14]
The output of Expand-Archive is quite verbose and can fill up the log files. At the least it's unfortunate to scroll past many lines of Expand-Archive output to get to the meat of the matter. Can you pipe the output of Expand-Archive to Out-Null?

**Comment by jhowardmsft** [comment]
Fixed by https://github.com/jhowardmsft/docker-w2wCIScripts/pull/16
