### ISSUE TITLE
"Get-ChildItem Env:" doesn't work for custom powershell hosts

### ISSUE THREAD

**Issue by mattkur** [jhowardmsft/docker-w2wCIScripts#15]
When running this in custom powershell hosts, simply using the output of "Get-ChildItem Env:" prints not useful stuff to the output. Instead Use Get-ChildItem Env: | Out-String .

Pass:   Invoking PowerShell Script
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
Info:   System.Collections.DictionaryEntry
StopTest:

**Comment by jhowardmsft** [comment]
Fixed by #16
